### ISSUE TITLE
error : syntax error, unexpected '?'

### ISSUE THREAD

**Issue by asrofilalbanna** [yajra/dt54#2]
Hi, first i apologize if my english so bad ...
Those i make wrong instalation or what ??

My step to install : 
1.    Configure your .env file.
2.    Run composer install
3.    Run php artisan migrate --seed
4.    Migrate error Specific key was too long and me add this in the AppServiceProvider.php (Fixed)
```
use Illuminate\Support\Facades\Schema;

public function boot()
{
    Schema::defaultStringLength(191);
}
```
      
4.    Then error Key pop up, but i use this 'php artisan key:generate' (Fixed)
5.    Then after generate key this (below) error show Idk how to fix this (NotFixed)
![image](https://user-images.githubusercontent.com/22786236/28742913-7acf9c46-7466-11e7-941b-9cf916925c63.png)

**Comment by yajra** [comment]
I think I have use PHP 7 specific code. Make sure you are using PHP 7+. Thanks!
