### ISSUE TITLE
Upgrade Laravel 5.4 to 5.5

### ISSUE THREAD

**Issue by jodykpw** [yajra/dt54#3]
Hi,

How can I upgrade laravel V 5.4 to 5.5?   i read laravel docs and can't upgrade. :(
Would like to have Laravel 5.5 New Features - Switch Statement for Blade Template.

My step to upgrade :
https://laravel.com/docs/5.5/upgrade
Update your laravel/framework dependency to 5.5.* in your composer.json file. In addition, you should update your phpunit/phpunit dependency to ~6.0.

composer update

Error:
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove barryvdh/laravel-snappy v0.3.3
    - Conclusion: don't install barryvdh/laravel-snappy v0.3.3
    - Conclusion: don't install laravel/framework v5.5.3
    - Conclusion: don't install laravel/framework v5.5.2
    - Conclusion: don't install laravel/framework v5.5.1
    - Installation request for barryvdh/laravel-snappy ^0.3.2 -> satisfiable by barryvdh/laravel-snappy[v0.3.2, v0.3.3].
    - Conclusion: don't install laravel/framework v5.5.0
    - barryvdh/laravel-snappy v0.3.2 requires illuminate/support 5.0.x|5.1.x|5.2.x|5.3.x|5.4.x -> satisfiable by laravel/framework[v5.4.27], illuminate/support[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.4.27].
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support 5.1.x-dev|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support 5.2.x-dev|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support 5.3.x-dev|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support 5.4.x-dev|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.0.0|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.0.22|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.0.25|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.0.26|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.0.28|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.0.33|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.0.4|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.1.1|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.1.13|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.1.16|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.1.2|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.1.20|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.1.22|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.1.25|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.1.28|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.1.30|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.1.31|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.1.41|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.1.6|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.1.8|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.2.0|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.2.19|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.2.21|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.2.24|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.2.25|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.2.26|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.2.27|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.2.28|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.2.31|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.2.32|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.2.37|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.2.43|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.2.45|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.2.6|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.2.7|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.3.0|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.3.16|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.3.23|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.3.4|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.4.0|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.4.13|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.4.17|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.4.19|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.4.27|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.4.36|don't install laravel/framework 5.5.x-dev
    - don't install illuminate/support v5.4.9|don't install laravel/framework 5.5.x-dev
    - Installation request for laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev, v5.5.0, v5.5.1, v5.5.2, v5.5.3].

Thanks all

**Comment by yajra** [comment]
Please see https://yajrabox.com/docs/laravel-datatables/master/upgrade for details. Thanks!

**Comment by ghost** [comment]
I am new to your Laravel DataTables implementation. I am looking for the DataTable tutorial version of Laravel 5.5 or compatible one. The indicated link (http://dt54.yajrabox.com/ ) does not work. It returns "Internal Server Error". Thanks.
